name: Publish API

on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Publish via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |

          echo 'Set Secret Values'
          export Email__Password='${{ secrets.EMAIL__PASSWORD }}'
          export Email__Host='${{ secrets.EMAIL__HOST }}'
          export Email__Address='${{ secrets.EMAIL__ADDRESS }}'
          export DynamoDB__secretKey='${{ secrets.DYNAMODB__SECRETKEY }}'
          export DynamoDB__accessKey='${{ secrets.DYNAMODB__ACCESSKEY }}'
          export Auth__TokenSecret='${{ secrets.AUTH__TOKENSECRET }}'
          export Auth__PasswordHashSecret='${{ secrets.AUTH__PASSWORDHASHSECRET }}'
          export FrontAppHost='${{ secrets.FRONTAPPHOST }}'
          export TsvUrl='${{ secrets.TSVURL }}'

          echo 'Open Repository folder'
          cd apps
          cd CongEspVilaGuilhermeApi
          
          echo 'Update data...'
          git pull
          git status
          sleep 5

          echo 'Stop server...'
          screen -XS "cong-esp-api" kill
          screen -ls
          sleep 5
          echo 'Starting server...'
          # screen -S cong-esp-api -d -m dotnet run --urls=http://*:8081
          
          sleep 5
          screen -ls

          sleep 5
          echo 'Publish on Docker and restart'
          docker compose up -d --build

          echo 'Sucessfully Published!'
